# 인터넷 상의 데이터 읽기
pandas.read_csv(url)
크롤링 통해 일기 selenium라이브러리 읽기
pandas.read_html(url,)
datareader라이브러리-내부적으로 requests 라이브러리 활용
seaborn 라이브러리

In [1]:
import pandas as pd

## pandas.read_csv(url)

In [6]:
df = pd.read_csv('https://people.sc.fsu.edu/~jburkardt/data/csv/biostats.csv', index_col = 'Name')
print(df.shape)
df.head()

(18, 4)

           "Sex"   "Age"   "Height (in)"   "Weight (lbs)"
Name
Alex         "M"      41              74              170
Bert         "M"      42              68              166
Carl         "M"      32              70              155
Dave         "M"      39              72              167
Elly         "F"      30              66              124

In [9]:
# loc 인덴서 활용 / 행 불러오기
df.loc['Alex']

     "Sex"                "M"
 "Age"                     41
 "Height (in)"             74
 "Weight (lbs)"           170
Name: Alex, dtype: object

## pandas.read_html 이용하기

In [17]:
df_list = pd.read_html('https://astro.kasi.re.kr/life/pageView/5')

In [18]:
len(df_list)

1

In [19]:
df = df_list[0]
df.head()

,ìë ¥,ìë ¥,ìë ¥ê°ì§
0,2020-04-01 (ì),2020-03-09,ê²½ì(åºå­)ë  ê²½ì§(åºè¾°)ì ê°ì (ç²...
1,2020-04-02 (ëª©),2020-03-10,ê²½ì(åºå­)ë  ê²½ì§(åºè¾°)ì ìí´(ä¹...
2,2020-04-03 (ê¸),2020-03-11,ê²½ì(åºå­)ë  ê²½ì§(åºè¾°)ì ë³ì(ä¸...
3,2020-04-04 (í ),2020-03-12,ê²½ì(åºå­)ë  ê²½ì§(åºè¾°)ì ì ì¶(ä¸...
4,2020-04-05 (ì¼),2020-03-13,ê²½ì(åºå­)ë  ê²½ì§(åºè¾°)ì ë¬´ì¸(æ...

In [20]:
# pip install --upgrade pandas-datareader

Collecting pandas-datareader
  Downloading pandas_datareader-0.8.1-py2.py3-none-any.whl (107 kB)
Requirement already satisfied, skipping upgrade: lxml in c:\anaconda3\lib\site-packages (from pandas-datareader) (4.5.0)
Requirement already satisfied, skipping upgrade: pandas>=0.21 in c:\anaconda3\lib\site-packages (from pandas-datareader) (1.0.1)
Requirement already satisfied, skipping upgrade: requests>=2.3.0 in c:\anaconda3\lib\site-packages (from pandas-datareader) (2.22.0)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in c:\anaconda3\lib\site-packages (from pandas>=0.21->pandas-datareader) (2019.3)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in c:\anaconda3\lib\site-packages (from pandas>=0.21->pandas-datareader) (1.18.1)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in c:\anaconda3\lib\site-packages (from pandas>=0.21->pandas-datareader) (2.8.1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\anaconda3\lib\site-packages (from requests>=2.3.0->pandas-datareader) (2019.11.28)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\anaconda3\lib\site-packages (from requests>=2.3.0->pandas-datareader) (2.8)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\anaconda3\lib\site-packages (from requests>=2.3.0->pandas-datareader) (1.25.8)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\anaconda3\lib\site-packages (from requests>=2.3.0->pandas-datareader) (3.0.4)
Requirement already satisfied, skipping upgrade: six>=1.5 in c:\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas>=0.21->pandas-datareader) (1.14.0)
Installing collected packages: pandas-datareader
Successfully installed pandas-datareader-0.8.1
Note: you may need to restart the kernel to use updated packages.

## pandas_datareader

In [24]:
# 주식정보

import pandas_datareader as pdr
pdr.get_data_yahoo('035420.KS', '2020-01-01')

                High       Low      Open     Close    Volume  Adj Close
Date
2020-01-02  188000.0  182000.0  187500.0  182500.0  300640.0   182500.0
2020-01-03  186000.0  180500.0  185000.0  181500.0  454492.0   181500.0
2020-01-06  182000.0  178000.0  180000.0  180500.0  287970.0   180500.0
2020-01-07  187000.0  181500.0  182500.0  187000.0  328624.0   187000.0
2020-01-08  183500.0  179000.0  182000.0  183000.0  820867.0   183000.0
2020-01-09  186500.0  183500.0  183500.0  186000.0  531355.0   186000.0
2020-01-10  188000.0  184000.0  185000.0  188000.0  398739.0   188000.0
2020-01-13  188500.0  186000.0  187500.0  188000.0  337749.0   188000.0
2020-01-14  194500.0  188000.0  188000.0  190500.0  501286.0   190500.0
2020-01-15  192000.0  188500.0  189500.0  191500.0  323778.0   191500.0
2020-01-16  192500.0  189000.0  190000.0  191500.0  245107.0   191500.0
2020-01-17  192500.0  189500.0  190500.0  191000.0  286019.0   191000.0
2020-01-20  190500.0  187000.0  190000.0  187500.0  454733.0   187500.0
2020-01-21  189500.0  181000.0  187500.0  182000.0  547678.0   182000.0
2020-01-22  190000.0  184500.0  185000.0  186000.0  429852.0   186000.0
2020-01-23  185500.0  181500.0  185000.0  183000.0  375929.0   183000.0
2020-01-28  184500.0  178000.0  182000.0  178500.0  476253.0   178500.0
2020-01-29  183500.0  180000.0  183000.0  180000.0  434897.0   180000.0
2020-01-30  183000.0  175000.0  179500.0  180000.0  772160.0   180000.0
2020-01-31  180500.0  177500.0  180000.0  179500.0  537062.0   179500.0
2020-02-03  180500.0  176000.0  178000.0  177500.0  485913.0   177500.0
2020-02-04  181500.0  175000.0  177500.0  180500.0  563463.0   180500.0
2020-02-05  183500.0  178500.0  181000.0  181500.0  653809.0   181500.0
2020-02-06  183500.0  180500.0  182500.0  181500.0  659850.0   181500.0
2020-02-07  188500.0  181000.0  181500.0  185000.0  728633.0   185000.0
2020-02-10  184000.0  180500.0  182500.0  183500.0  433051.0   183500.0
2020-02-11  185000.0  183000.0  183500.0  184500.0  400386.0   184500.0
2020-02-12  185000.0  181500.0  183000.0  185000.0  351892.0   185000.0
2020-02-13  185000.0  183000.0  184000.0  184500.0  555923.0   184500.0
2020-02-14  187500.0  184000.0  184000.0  186500.0  659429.0   186500.0
2020-02-17  189000.0  184500.0  184500.0  188500.0  312407.0   188500.0
2020-02-18  188500.0  185500.0  186500.0  186500.0  345642.0   186500.0
2020-02-19  191000.0  185000.0  188000.0  189500.0  560743.0   189500.0
2020-02-20  191500.0  187500.0  189500.0  190000.0  427402.0   190000.0
2020-02-21  191000.0  187000.0  187500.0  189500.0  434019.0   189500.0
2020-02-24  187500.0  183500.0  185500.0  184000.0  567036.0   184000.0
2020-02-25  191000.0  183500.0  184000.0  190500.0  704859.0   190500.0
2020-02-26  190000.0  186500.0  189500.0  187000.0  494066.0   187000.0
2020-02-27  187000.0  179000.0  185000.0  182000.0  535696.0   182000.0
2020-02-28  180000.0  172000.0  179000.0  174000.0  830654.0   174000.0
2020-03-02  177000.0  172500.0  175000.0  175000.0  659376.0   175000.0
2020-03-03  180000.0  174000.0  179000.0  175000.0  544379.0   175000.0
2020-03-04  179500.0  173000.0  174500.0  178500.0  450252.0   178500.0
2020-03-05  181000.0  178500.0  180500.0  181000.0  483840.0   181000.0
2020-03-06  181000.0  177500.0  179500.0  179500.0  293897.0   179500.0
2020-03-09  179500.0  179500.0  179500.0  179500.0       0.0   179500.0
2020-03-10  176000.0  165000.0  168000.0  172000.0  666532.0   172000.0
2020-03-11  174000.0  167500.0  172000.0  170000.0  483822.0   170000.0
2020-03-12  170000.0  170000.0  170000.0  170000.0       0.0   170000.0
2020-04-03  172500.0  168000.0  170000.0  172000.0  641347.0   172000.0